from datetime import datetime, UTC
from logging.handlers import BufferingHandler
from uuid import uuid4

from oci import loggingingestion

"""OciLoggingHandler is a buffered logger that sends logs generated by the Python logging
   library to the OCI Logging service. Subclass of logging.BufferingHandler to take advantage
   of batch log entries in OCI SDK.
"""
class OciLoggingHandler(BufferingHandler):
    def __init__(self, log_ocid: str, config: dict, capacity: int):
        super().__init__(capacity)
        self.log_ocid = log_ocid
        self.client = loggingingestion.LoggingClient(config)

    def flush(self):
        entries = []
        for record in self.buffer:
            entries.append(loggingingestion.models.LogEntry(
                data=self.format(record),
                id=str(uuid4()),
                time=datetime.fromtimestamp(record.created).astimezone(UTC)
            ))

        details = loggingingestion.models.PutLogsDetails(
            specversion="1.0",
            log_entry_batches = [loggingingestion.models.LogEntryBatch(
                defaultlogentrytime=datetime.now(UTC),
                source="Python Logger",
                type="python_application",
                entries=entries
            )]
        )

        response = self.client.put_logs(self.log_ocid, details)
        #print(f'Response Status Code: {response.status}')

        self.buffer.clear()